config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'

  resources :items do
    get 'confirm', on: :collection
    get 'itemsuser', on: :collection
  end
  resources :users do
    get 'logout', on: :collection
    get 'profile', on: :collection
  end
  resources :users, only: [:index,:show]
  resources :creditcards, only: [:index]
  resources :items_buy_confirms, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_one :item
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, through: :item_categories
  has_many :item_categories
  has_one :item
end

app/models/child_category.rb
class ChildCategory < ApplicationRecord
  has_one :item
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user
  belongs_to :trade
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :user
end

app/models/grandchild_category.rb
class GrandchildCategory < ApplicationRecord
  has_one :item
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :user
  belongs_to :brand, optional: true
  belongs_to :category, optional: true
  belongs_to :child_category, optional: true
  belongs_to :grandchild_category, optional: true
  has_one :trade
  has_one :card
  has_many :likes
  has_many :comments
  has_many :categories, through: :item_categories
  has_many :item_categories
  has_many :images

  def previous
    Item.order('id DESC').where('id < ?',self.id).first
  end

  def next
    Item.order('id ASC').where('? < id', self.id).first
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/trade.rb
class Trade < ApplicationRecord
  has_many :comments
  belongs_to :item
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items
  has_many :comments
  has_many :buyers
  has_many :evaluations
  has_many :likes
  has_many :trades

  validates_confirmation_of :password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth, if: :production?
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def production?
    Rails.env.production?
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname,:family_name,:first_name,:family_name_kana,:first_name_kana,:year,:month,:day])
  end
end

app/controllers/creditcards_controller.rb
class CreditcardsController < ApplicationController

  def index
  end

end

app/controllers/items_buy_confirms_controller.rb
class ItemsBuyConfirmsController < ApplicationController

  def index
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
    @ladies = index_select.where(category_id: 1)
    @mens = index_select.where(category_id: 2)
    @babies = index_select.where(category_id: 3)
    @cosmes = index_select.where(category_id: 4)
    @chanels = index_select.where(brand_id: 1)
    @vuittones = index_select.where(brand_id: 2)
    @supremes = index_select.where(brand_id: 3)
    @nikes = index_select.where(brand_id: 4)
  end

  def show
    # @item = Item.find(params[:id])
    # @items = Item.includes(:user).order("id DESC")
    # @image = Image.find(params[:id])
    # @images = @item.images.includes(:item)
    # @list = Image.includes(:item)
  end

  def confirm
  end

  def new
  end

  private
  def index_select
    @items.order("created_at DESC").limit(4)
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def logout
  end


  def new
  end

  def profile
  end

  def show
    require 'yaml'
    @value = YAML.load_file('config/prefecture-select.yml')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/creditcards/index.html.haml
= render 'layouts/header'
.double-large-container.margin-bottom_40
  = render 'users/side-bar'
  .l-single-container.mypage-confirm-box.end-of-contents
    %h2 クレジットカード情報入力
    .form-wrap
      %form.user-confirm-form.creditcard-form
        .user-confirm-form--column.form-group
          %label{for: "card-num"}
            %span.require カード番号
          %input#card-num{name: "", placeholder: "半角数字のみ", type: "number"}/
          %ul.card-logo
            %li.card-logo--visa= image_tag('visa.svg')
            %li.card-logo--master= image_tag('master.svg')
            %li.card-logo--saison= image_tag('saison.svg')
            %li.card-logo--jcb= image_tag('jcb.svg')
            %li.card-logo--amex= image_tag('amex.svg')
            %li.card-logo--diners= image_tag('diners.svg')
            %li.card-logo--discover= image_tag('discover.svg')
        .user-confirm-form--column.form-group
          %label{for: "card-date-month"}
            %span.require 有効期限
          .select-wrap-small.column-parallel_left
            %select#card-date-month.select-small{name: "", required: ""}
              %option{value: ""} --
            %span.unit 月
          .select-wrap-small.column-parallel_left
            %select.select-small{name: "", required: ""}
              %option{value: ""} --
            %span.unit 年
        .user-confirm-form--column.form-group
          %label{for: "card-num"}
            %span.require セキュリティコード
          %input#card-num{name: "", placeholder: "半角数字のみ", type: "number"}/
          %p.card-text-right= link_to 'カード裏面の番号とは？','#'
        %button.btn-small.background-color_red.margin-top_30{type: "submit"} 追加する
= render partial: "layouts/sale_item_btn"

app/views/items/confirm.html.haml
= render partial: "layouts/users_header"
%section
  .l-single-container.signup-title
    %h2 購入を確定しますか？
  .l-single-container.buy-confirm
    .buy-confirm--image
      = image_tag('m31884463082_1.jpg', alt: '商品タイトル商品タイトル商品タイトル')
    %h3.item-title ショートパンツ
    .buy-confirm--price
      %p.price ¥ 9,999,999
      %p.item-shipping-fee 着払い
    .buy-confirm--btn
      = link_to 'ポイントはありません', '#', class: 'btn-small background-color_btn-gray'
    .final-confirm-price
      %p.final-confirm-price--title 支払い金額
      %p.final-confirm-price--price ¥ 9,999,999
    .buy-confirm--btn
      = link_to '購入する', '#', class: 'btn-small background-color_red buy-btn'
  .l-single-container.buy-confirm
    .buy-user-info
      %h3.buy-user-info--title 配送先
      %p.buy-user-info--postnum 165-0000
      %p 東京都中野区中野中野10-10 メルカリハイツ
      %p 庄司 美雪
    %p.user-info-edit
      = link_to "変更する",'#', class: 'blue-link mark-next'
  .l-single-container.buy-confirm
    .buy-user-info.user-payment
      %h3.buy-user-info--title 支払い方法
      %p ************0000
      %p 04 / 28
      %p.card-logo
        = image_tag('card-logo-jcb.svg', alt: 'JCB')
    %p.user-info-edit
      = link_to "変更する",'#', class: 'blue-link mark-next'
= render partial: "layouts/users_footer"

app/views/items/index.html.haml
= render partial: "layouts/header"
/ カルーセル
%div
  .single-slider-item
    %div
      = link_to '#' do
        = image_tag('banner-hajimeru-fortune.jpg', alt: 'mercari')
    %div
      = link_to '#' do
        = image_tag('banner-featured-hobby.jpg', alt: 'mercari')
    .top-banner.bg-image-room
      .top-banner--inner.container
        .left
          %h2
            スマホでかんたん
            %br>/
            フリマアプリ
          %p
            メルカリはスマホカメラからすぐに出品できる
            %br>/
            購入時も安心な独自システムのアプリです
          .app-link
            = link_to '#' do
              = image_tag('app-store.svg', alt: 'appstore')
            = link_to '#' do
              = image_tag('google-play.svg', alt: 'googleplay')
        .right
          = image_tag('main_content_pc.png')
    %div
      = link_to '#' do
        = image_tag('banner-bokurano-heisei-entertainment.png', alt: 'mercari')
    %div
      = link_to '#' do
        = image_tag('banner-bokurano-heisei.jpg', alt: 'mercari')
  .top-image-sp
    = image_tag('banner-hajimeru-fortune.jpg', alt: 'mercari')
/ カルーセル
.pickup.container
  %h2 ピックアップカテゴリー
  %section.top-items.container
    / 繰り返し
    %h3= link_to 'レディース 新着アイテム', "#"
    .item-line
      - @ladies.each do |lady|
        = link_to '#' do
          .items-box
            %figure.items-box--image
              = image_tag(lady.images[0].name, alt: '商品タイトル商品タイトル商品タイトル')
            .item--caption
              %h4
                = lady.name
              %div
                %p.price
                  = "¥ #{lady.price}"
                %p.like
                  %i.far.fa-heart.like-icon
                  1
                %p (税込)
    %p.link-to-all
      = link_to 'すべての商品を見る', "#"
  %section.top-items.container
    / 繰り返し
    %h3= link_to 'メンズ 新着アイテム', "#"
    .item-line
      - @mens.each do |men|
        = link_to '#' do
          .items-box
            %figure.items-box--image
              = image_tag(men.images[0].name, alt: '商品タイトル商品タイトル商品タイトル')
            .item--caption
              %h4
                = men.name
              %div
                %p.price
                  = "¥ #{men.price}"
                %p.like
                  %i.far.fa-heart.like-icon
                  1
                %p (税込)
    %p.link-to-all
      = link_to 'すべての商品を見る', "#"
  %section.top-items.container
    / 繰り返し
    %h3= link_to 'ベビー・キッズ 新着アイテム', "#"
    .item-line
      - @babies.each do |baby|
        = link_to '#' do
          .items-box
            %figure.items-box--image
              = image_tag(baby.images[0].name, alt: '商品タイトル商品タイトル商品タイトル')
            .item--caption
              %h4
                = baby.name
              %div
                %p.price
                  = "¥ #{baby.price}"
                %p.like
                  %i.far.fa-heart.like-icon
                  1
                %p (税込)
    %p.link-to-all
      = link_to 'すべての商品を見る', "#"
  %section.top-items.container
    / 繰り返し
    %h3= link_to 'コスメ・香水・美容 新着アイテム', "#"
    .item-line
      - @cosmes.each do |cosme|
        = link_to '#' do
          .items-box
            %figure.items-box--image
              = image_tag(cosme.images[0].name, alt: '商品タイトル商品タイトル商品タイトル')
            .item--caption
              %h4
                = cosme.name
              %div
                %p.price
                  = "¥ #{cosme.price}"
                %p.like
                  %i.far.fa-heart.like-icon
                  1
                %p (税込)
    %p.link-to-all
      = link_to 'すべての商品を見る', "#"
.pickup.container
  %h2 ピックアップブランド
  %section.top-items.container
    / 繰り返し
    %h3= link_to 'シャネル 新着アイテム', "#"
    .item-line
      - @chanels.each do |chanel|
        = link_to '#' do
          .items-box
            %figure.items-box--image
              = image_tag(chanel.images[0].name, alt: '商品タイトル商品タイトル商品タイトル')
            .item--caption
              %h4
                = chanel.name
              %div
                %p.price
                  = "¥ #{chanel.price}"
                %p.like
                  %i.far.fa-heart.like-icon
                  1
                %p (税込)
    %p.link-to-all= link_to 'すべての商品を見る', "#"
  %section.top-items.container
    / 繰り返し
    %h3= link_to 'ルイヴィトン 新着アイテム', "#"
    .item-line
      - @vuittones.each do |vuittone|
        = link_to '#' do
          .items-box
            %figure.items-box--image
              = image_tag(vuittone.images[0].name, alt: '商品タイトル商品タイトル商品タイトル')
            .item--caption
              %h4
                = vuittone.name
              %div
                %p.price
                  = "¥ #{vuittone.price}"
                %p.like
                  %i.far.fa-heart.like-icon
                  1
                %p (税込)
    %p.link-to-all= link_to 'すべての商品を見る', "#"
  %section.top-items.container
    / 繰り返し
    %h3= link_to 'シュプリーム 新着アイテム', "#"
    .item-line
      - @supremes.each do |supreme|
        = link_to '#' do
          .items-box
            %figure.items-box--image
              = image_tag(supreme.images[0].name, alt: '商品タイトル商品タイトル商品タイトル')
            .item--caption
              %h4
                = supreme.name
              %div
                %p.price
                  = "¥ #{supreme.price}"
                %p.like
                  %i.far.fa-heart.like-icon
                  1
                %p (税込)
    %p.link-to-all= link_to 'すべての商品を見る', "#"
  %section.top-items.container
    / 繰り返し
    %h3= link_to 'ナイキ 新着アイテム', "#"
    .item-line
      - @nikes.each do |nike|
        = link_to '#' do
          .items-box
            %figure.items-box--image
              = image_tag(nike.images[0].name, alt: '商品タイトル商品タイトル商品タイトル')
            .item--caption
              %h4
                = nike.name
              %div
                %p.price
                  = "¥ #{nike.price}"
                %p.like
                  %i.far.fa-heart.like-icon
                  1
                %p (税込)
    %p.link-to-all= link_to 'すべての商品を見る', "#"
= render partial: "layouts/sale_item_btn"
= render partial: "layouts/footer"

app/views/items_buy_confirms/index.html.haml
= render partial: "layouts/users_header"
%section
  .l-single-container.signup-title
    %h2 購入を確定しますか？
  .l-single-container.buy-confirm
    .buy-confirm--image
      = image_tag('https://base-ec2.akamaized.net/images/item/origin/26b44e0e8c8c1079cedf032f7c48b276.png', alt: 'ハンサム')
    %h3.item-title ハンサム5人
    .buy-confirm--price
      %p.price ¥ 836
      %p.item-shipping-fee 着払い
    .buy-confirm--btn
      = link_to 'ポイントはありません', '#', class: 'btn-small background-color_btn-gray'
    .final-confirm-price
      %p.final-confirm-price--title 支払い金額
      %p.final-confirm-price--price ¥ 836
    .buy-confirm--btn
      = link_to '購入する', '#', class: 'btn-small background-color_red buy-btn'
  .l-single-container.buy-confirm
    .buy-user-info
      %h3.buy-user-info--title 配送先
      %p.buy-user-info--postnum 165-0000
      %p 東京都中野区中野中野10-10 メルカリハイツ
      %p 庄司 美雪
    %p.user-info-edit
      = link_to "変更する",'#', class: 'blue-link mark-next'
  .l-single-container.buy-confirm
    .buy-user-info.user-payment
      %h3.buy-user-info--title 支払い方法
      %p ************0000
      %p 04 / 28
      %p.card-logo
        = image_tag('card-logo-jcb.svg', alt: 'JCB')
    %p.user-info-edit
      = link_to "変更する",'#', class: 'blue-link mark-next'
= render partial: "layouts/users_footer"

app/views/layouts/_header2.html.haml
%header
  .header-inner
    .header-inner--top
      .logo
        = link_to "/items/itemsuser" do
          %img{alt: "mercari", src: "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?817106341"}/
      .search-form.search-form-width
        %form
          %input.search-form-width{name: "search-item", placeholder: "キーワードから探す", type: "text"}/
          %button
            %i.fas.fa-search.search-icon-size
    .header-bottom
      .header-bottom--left
        %ul.header-search-item.menu
          %li
            %a{href: "#"} カテゴリーから探す
          %li.menu__single.padding-left_15
            %a.init-bottom{href: "#"} ブランドから探す
            %ul.menu__second-level
              %li
                %a{href: "#"} シャネル
              %li
                %a{href: "#"} ナイキ
              %li
                %a{href: "#"} ルイ ヴィトン
              %li
                %a{href: "#"} シュプリーム
              %li
                %a{href: "#"} アディダス
              %li
                %a{href: "#"} ブランド一覧
      .header-bottom--right
        %ul.links
          %li
            = link_to "/users/" do
              %span
                %img{alt: "", src: "https://mcdn.mercariapp.com/images/member_photo_noimage_thumb.png"}/
              %p マイページ
          %li
            %a{href: "#"}
              %span.header-icon
                %i.far.fa-bell
              %p お知らせ
          %li
            %a{href: "#"}
              %span.header-icon
                %i.fas.fa-check
              %p やることリスト
    #nav-wrapper
      %nav.nav-menu
        %ul
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              マイページ
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              お知らせ
              .badge-num.sp-none
                5
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              やることリスト
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              いいね！一覧
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              出品する
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              出品した商品 - 出品中
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              出品した商品 - 取引中
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              出品した商品 - 売却済み
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              購入した商品-取引中
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              購入した商品-過去の取引
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              ニュース一覧
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              評価一覧
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              ガイド
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              お問い合わせ
              %i.fas.fa-angle-right
      %button{id: "nav-btn", type: "button", class: "hamburger"}
        %span.bdr
        %span.bdr
        %span.bdr

app/views/layouts/_header_mypage.html.haml
%header
  .header-inner
    .header-inner--top
      .logo
        %img{alt: "mercari", src: "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?817106341"}/
      .search-form.search-form-width
        %form
          %input.search-form-width{name: "search-item", placeholder: "キーワードから探す", type: "text"}/
          %button
            %i.fas.fa-search.search-icon-size
    .header-bottom
      .header-bottom--left
        %ul.header-search-item.menu
          %li
            %a{href: "#"} カテゴリーから探す
          %li.menu__single.padding-left_15
            %a.init-bottom{href: "#"} ブランドから探す
            %ul.menu__second-level
              %li
                %a{href: "#"} シャネル
              %li
                %a{href: "#"} ナイキ
              %li
                %a{href: "#"} ルイ ヴィトン
              %li
                %a{href: "#"} シュプリーム
              %li
                %a{href: "#"} アディダス
              %li
                %a{href: "#"} ブランド一覧
      .header-bottom--right
        %ul.links
          %li
            %a{href: "#"}
              %span
                %img{alt: "", src: "https://mcdn.mercariapp.com/images/member_photo_noimage_thumb.png"}/
              %p マイページ
          %li
            %a{href: "#"}
              %span.header-icon
                %i.far.fa-bell
              %p お知らせ
          %li
            %a{href: "#"}
              %span.header-icon
                %i.fas.fa-check
              %p やることリスト
    #nav-wrapper
      %nav.nav-menu
        %ul
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              マイページ
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              お知らせ
              .badge-num.sp-none
                5
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              やることリスト
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              いいね！一覧
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              出品する
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              出品した商品 - 出品中
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              出品した商品 - 取引中
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              出品した商品 - 売却済み
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              購入した商品-取引中
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              購入した商品-過去の取引
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              ニュース一覧
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              評価一覧
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              ガイド
              %i.fas.fa-angle-right
          %li
            = link_to users_path, class: "mypage-nav-list_item" do
              お問い合わせ
              %i.fas.fa-angle-right
      %button{id: "nav-btn", type: "button", class: "hamburger"}
        %span.bdr
        %span.bdr
        %span.bdr

app/views/layouts/_sale_item_btn.haml
= link_to new_item_path, class: "background-color_red put-item" do
  .put-item--inner
    %p 出品
    %i.fas.fa-camera.icon-camera

app/views/layouts/_users_footer.html.haml
%footer.user-sign-up--footer
  %ul.container
    %li
      = link_to "プライバシーポリシー",'#'
    %li
      = link_to "メルカリ利用規約",'#'
    %li
      = link_to "特定商取引に関する表記",'#'
  .footer-logo--signup.container
    = link_to "/items/itemsuser" do
      = image_tag("mercari-logo-gray.svg",alt: 'mercari' )
    %p © 2019 Mercari

app/views/layouts/_users_header.html.haml
%body
  %header.user-sign-up-header
    %h1.user-sign-up-header--logo
      = link_to "/items/itemsuser" do
        = image_tag("mercari-logo.svg",alt: 'mercari' )

app/views/users/_side-bar.html.haml
.side-bar.sp-none
  .mypage-nav
    %ul.mypage-nav-list
      %li
        = link_to users_path, class: "mypage-nav-list_item" do
          マイページ
          %i.fas.fa-angle-right
      %li
        = link_to users_path, class: "mypage-nav-list_item" do
          お知らせ
          .badge-num.sp-none
            5
          %i.fas.fa-angle-right
      %li
        = link_to users_path, class: "mypage-nav-list_item" do
          やることリスト
          %i.fas.fa-angle-right
      %li
        = link_to users_path, class: "mypage-nav-list_item" do
          いいね！一覧
          %i.fas.fa-angle-right
      %li
        = link_to '/items/new', class: "mypage-nav-list_item" do
          出品する
          %i.fas.fa-angle-right
      %li
        = link_to users_path, class: "mypage-nav-list_item" do
          出品した商品-出品中
          %i.fas.fa-angle-right
      %li
        = link_to users_path, class: "mypage-nav-list_item" do
          出品した商品-取引中
          %i.fas.fa-angle-right
      %li
        = link_to users_path, class: "mypage-nav-list_item" do
          出品した商品-売却済み
          %i.fas.fa-angle-right
      %li
        = link_to users_path, class: "mypage-nav-list_item" do
          購入した商品-取引中
          %i.fas.fa-angle-right
      %li
        = link_to users_path, class: "mypage-nav-list_item" do
          購入した商品-過去の取引
          %i.fas.fa-angle-right
      %li
        = link_to users_path, class: "mypage-nav-list_item" do
          ニュース一覧
          %i.fas.fa-angle-right
      %li
        = link_to users_path, class: "mypage-nav-list_item" do
          評価一覧
          %i.fas.fa-angle-right
      %li
        = link_to users_path, class: "mypage-nav-list_item" do
          ガイド
          %i.fas.fa-angle-right
      %li
        = link_to users_path, class: "mypage-nav-list_item" do
          お問い合わせ
          %i.fas.fa-angle-right

    %h3.mypage-nav-head
      売上・ポイント
    %ul.mypage-nav-list
      %li
        = link_to users_path, class: "mypage-nav-list_item" do
          売上・振込申請
          %i.fas.fa-angle-right
      %li
        = link_to users_path, class: "mypage-nav-list_item" do
          ポイント
          %i.fas.fa-angle-right
    %h3.mypage-nav-head
      設定
    %ul.mypage-nav-list
      %li
        = link_to profile_users_path, class: "mypage-nav-list_item" do
          プロフィール
          %i.fas.fa-angle-right
      %li
        = link_to users_path, class: "mypage-nav-list_item" do
          住所変更
          %i.fas.fa-angle-right
      %li
        = link_to users_path, class: "mypage-nav-list_item" do
          支払い方法
          %i.fas.fa-angle-right
      %li
        = link_to users_path, class: "mypage-nav-list_item" do
          メール/パスワード
          %i.fas.fa-angle-right
      %li
        = link_to "/users/show", class: "mypage-nav-list_item" do
          本人情報
          %i.fas.fa-angle-right
      %li
        = link_to users_path, class: "mypage-nav-list_item" do
          電話番号の確認
          %i.fas.fa-angle-right
      %li
        = link_to logout_users_path, class: "mypage-nav-list_item" do
          ログアウト
          %i.fas.fa-angle-right

app/views/users/index.html.haml
= render 'layouts/header_mypage'
.l-container.clearfix
  = render "mypage"
  = render "side-bar"
= render partial: "layouts/footer"

app/views/users/profile.html.haml
= render 'layouts/header_mypage'
.l-container.clearfix
  .l-content
    .profile
      =form_tag do
        .profile-head
          %h2
            プロフィール
          .setting-profile
            .setting-profile__icon
              .setting-profile__icon--image
                = image_tag "//mcdn.mercariapp.com/images/member_photo_noimage_thumb.png"
              = text_field_tag :nickname, "", {class: "setting-profile__icon--nickname", placeholder: "例)AYA☆セール中"}
        .profile-content
          =text_area_tag :comment,"", {class: "profile-content__comment", placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪"}
          = link_to "変更する", users_path, method: :update, class: "profile-content__submit"
  = render "side-bar"
= render partial: "layouts/footer"